testplatform.c: always use %I64 instead of %ll for all windows builds;
fixes MinGW gcc warnings:

testplatform.c:115:3: warning: unknown conversion type character 'l' in format
testplatform.c:115:3: warning: unknown conversion type character 'l' in format
testplatform.c:115:3: warning: too many arguments for format